import os
import sys
from datetime import date, timedelta
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker

# Add project root to sys.path
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from app.core.config import settings
from app.core.database import Base, engine, SessionLocal
from app.models.pharmacy import PharmacyItem

MEDICINES_DATA = [
    {
        "brand_name": "Dolo 650mg Tab",
        "drug_name": "Paracetamol 650mg",
        "category": "Tablet",
        "batch_number": "DOL-2026-081",
        "expiry_date": date.today() + timedelta(days=540),
        "stock_quantity": 250,
        "reorder_level": 30,
        "unit_price": 3.50,
    },
    {
        "brand_name": "Panpro 40mg Tab",
        "drug_name": "Pantoprazole 40mg",
        "category": "Tablet",
        "batch_number": "PAN-2026-112",
        "expiry_date": date.today() + timedelta(days=620),
        "stock_quantity": 180,
        "reorder_level": 25,
        "unit_price": 9.00,
    },
    {
        "brand_name": "Augmentin 625 Duo Tab",
        "drug_name": "Amoxicillin + Clavulanic Acid 625mg",
        "category": "Tablet",
        "batch_number": "AUG-2026-204",
        "expiry_date": date.today() + timedelta(days=480),
        "stock_quantity": 120,
        "reorder_level": 20,
        "unit_price": 22.50,
    },
    {
        "brand_name": "Gramocef 200mg Tab",
        "drug_name": "Cefixime 200mg",
        "category": "Tablet",
        "batch_number": "GRA-2026-095",
        "expiry_date": date.today() + timedelta(days=420),
        "stock_quantity": 90,
        "reorder_level": 15,
        "unit_price": 14.00,
    },
    {
        "brand_name": "Zental 400mg Tab",
        "drug_name": "Albendazole 400mg",
        "category": "Chewable Tab",
        "batch_number": "ZEN-2026-044",
        "expiry_date": date.today() + timedelta(days=730),
        "stock_quantity": 40,
        "reorder_level": 10,
        "unit_price": 16.00,
    },
    {
        "brand_name": "Gelusil MPS Syrup 200ml",
        "drug_name": "Aluminium Hydroxide + Magnesium Hydroxide + Simethicone",
        "category": "Syrup",
        "batch_number": "GEL-2026-180",
        "expiry_date": date.today() + timedelta(days=365),
        "stock_quantity": 35,
        "reorder_level": 10,
        "unit_price": 115.00,
    },
    {
        "brand_name": "Alerlife-LS Syrup 100ml",
        "drug_name": "Levosalbutamol + Ambroxol + Guaiphenesin",
        "category": "Syrup",
        "batch_number": "ALE-2026-067",
        "expiry_date": date.today() + timedelta(days=300),
        "stock_quantity": 45,
        "reorder_level": 10,
        "unit_price": 95.00,
    },
    {
        "brand_name": "Alprax 0.5mg Tab",
        "drug_name": "Alprazolam 0.5mg",
        "category": "Tablet",
        "batch_number": "ALP-2026-023",
        "expiry_date": date.today() + timedelta(days=600),
        "stock_quantity": 15,  # Low stock test
        "reorder_level": 20,
        "unit_price": 4.50,
    },
    {
        "brand_name": "Calpol 500mg Tab",
        "drug_name": "Paracetamol 500mg",
        "category": "Tablet",
        "batch_number": "CAL-2026-301",
        "expiry_date": date.today() + timedelta(days=700),
        "stock_quantity": 300,
        "reorder_level": 50,
        "unit_price": 2.50,
    },
    {
        "brand_name": "Ascoril D Plus Syrup 100ml",
        "drug_name": "Dextromethorphan + Phenylephrine + Chlorpheniramine",
        "category": "Syrup",
        "batch_number": "ASC-2026-145",
        "expiry_date": date.today() + timedelta(days=400),
        "stock_quantity": 50,
        "reorder_level": 15,
        "unit_price": 120.00,
    },
    {
        "brand_name": "Montek LC Tab",
        "drug_name": "Montelukast 10mg + Levocetirizine 5mg",
        "category": "Tablet",
        "batch_number": "MON-2026-512",
        "expiry_date": date.today() + timedelta(days=550),
        "stock_quantity": 160,
        "reorder_level": 25,
        "unit_price": 18.00,
    },
    {
        "brand_name": "Azithral 500mg Tab",
        "drug_name": "Azithromycin 500mg",
        "category": "Tablet",
        "batch_number": "AZI-2026-319",
        "expiry_date": date.today() + timedelta(days=650),
        "stock_quantity": 110,
        "reorder_level": 20,
        "unit_price": 24.00,
    },
    {
        "brand_name": "Telma 40mg Tab",
        "drug_name": "Telmisartan 40mg",
        "category": "Tablet",
        "batch_number": "TEL-2026-882",
        "expiry_date": date.today() + timedelta(days=720),
        "stock_quantity": 140,
        "reorder_level": 20,
        "unit_price": 12.50,
    },
    {
        "brand_name": "Glycomet 500mg Tab",
        "drug_name": "Metformin Hydrochloride 500mg",
        "category": "Tablet",
        "batch_number": "GLY-2026-440",
        "expiry_date": date.today() + timedelta(days=580),
        "stock_quantity": 220,
        "reorder_level": 30,
        "unit_price": 3.00,
    },
    {
        "brand_name": "Shelcal 500mg Tab",
        "drug_name": "Calcium 500mg + Vitamin D3 250IU",
        "category": "Tablet",
        "batch_number": "SHE-2026-903",
        "expiry_date": date.today() + timedelta(days=610),
        "stock_quantity": 190,
        "reorder_level": 25,
        "unit_price": 8.50,
    },
    {
        "brand_name": "Becosules Z Cap",
        "drug_name": "Vitamin B-Complex + Vitamin C + Zinc",
        "category": "Capsule",
        "batch_number": "BEC-2026-721",
        "expiry_date": date.today() + timedelta(days=450),
        "stock_quantity": 280,
        "reorder_level": 40,
        "unit_price": 5.00,
    },
    {
        "brand_name": "Volini Gel 30g",
        "drug_name": "Diclofenac Diethylamine + Linseed Oil + Menthol",
        "category": "Ointment",
        "batch_number": "VOL-2026-118",
        "expiry_date": date.today() + timedelta(days=500),
        "stock_quantity": 40,
        "reorder_level": 10,
        "unit_price": 85.00,
    },
    {
        "brand_name": "Combiflam Tab",
        "drug_name": "Ibuprofen 400mg + Paracetamol 325mg",
        "category": "Tablet",
        "batch_number": "COM-2026-367",
        "expiry_date": date.today() + timedelta(days=640),
        "stock_quantity": 240,
        "reorder_level": 30,
        "unit_price": 4.00,
    },
    {
        "brand_name": "Cetzine 10mg Tab",
        "drug_name": "Cetirizine Dihydrochloride 10mg",
        "category": "Tablet",
        "batch_number": "CET-2026-190",
        "expiry_date": date.today() + timedelta(days=520),
        "stock_quantity": 180,
        "reorder_level": 25,
        "unit_price": 4.50,
    },
    {
        "brand_name": "Omez 20mg Cap",
        "drug_name": "Omeprazole 20mg",
        "category": "Capsule",
        "batch_number": "OME-2026-805",
        "expiry_date": date.today() + timedelta(days=600),
        "stock_quantity": 210,
        "reorder_level": 30,
        "unit_price": 6.50,
    },
    {
        "brand_name": "Meftal Spas Tab",
        "drug_name": "Mefenamic Acid 250mg + Dicyclomine 10mg",
        "category": "Tablet",
        "batch_number": "MEF-2026-033",
        "expiry_date": date.today() + timedelta(days=480),
        "stock_quantity": 85,
        "reorder_level": 15,
        "unit_price": 6.00,
    },
    {
        "brand_name": "Clavam 625 Tab",
        "drug_name": "Amoxicillin 500mg + Potassium Clavulanate 125mg",
        "category": "Tablet",
        "batch_number": "CLA-2026-614",
        "expiry_date": date.today() + timedelta(days=410),
        "stock_quantity": 95,
        "reorder_level": 20,
        "unit_price": 21.00,
    },
    {
        "brand_name": "Taxim-O 200mg Tab",
        "drug_name": "Cefixime 200mg",
        "category": "Tablet",
        "batch_number": "TAX-2026-218",
        "expiry_date": date.today() + timedelta(days=530),
        "stock_quantity": 70,
        "reorder_level": 15,
        "unit_price": 13.50,
    },
    {
        "brand_name": "Allegra 120mg Tab",
        "drug_name": "Fexofenadine Hydrochloride 120mg",
        "category": "Tablet",
        "batch_number": "ALL-2026-789",
        "expiry_date": date.today() + timedelta(days=590),
        "stock_quantity": 65,
        "reorder_level": 15,
        "unit_price": 19.00,
    },
    {
        "brand_name": "Rantac 150mg Tab",
        "drug_name": "Ranitidine Hydrochloride 150mg",
        "category": "Tablet",
        "batch_number": "RAN-2026-402",
        "expiry_date": date.today() + timedelta(days=380),
        "stock_quantity": 150,
        "reorder_level": 25,
        "unit_price": 3.20,
    },
    {
        "brand_name": "Supradyn Daily Tab",
        "drug_name": "Multivitamins with Minerals & Trace Elements",
        "category": "Tablet",
        "batch_number": "SUP-2026-950",
        "expiry_date": date.today() + timedelta(days=670),
        "stock_quantity": 175,
        "reorder_level": 25,
        "unit_price": 6.50,
    },
    {
        "brand_name": "Neurobion Forte Tab",
        "drug_name": "Vitamin B12 + B6 + B1 + Nicotinamide",
        "category": "Tablet",
        "batch_number": "NEU-2026-881",
        "expiry_date": date.today() + timedelta(days=710),
        "stock_quantity": 320,
        "reorder_level": 40,
        "unit_price": 3.80,
    },
    {
        "brand_name": "Dulcoflex 5mg Tab",
        "drug_name": "Bisacodyl 5mg",
        "category": "Tablet",
        "batch_number": "DUL-2026-119",
        "expiry_date": date.today() + timedelta(days=620),
        "stock_quantity": 120,
        "reorder_level": 20,
        "unit_price": 2.00,
    },
    {
        "brand_name": "Digene Gel Orange 200ml",
        "drug_name": "Magnesium Hydroxide + Aluminium Hydroxide + Simethicone",
        "category": "Syrup",
        "batch_number": "DIG-2026-554",
        "expiry_date": date.today() + timedelta(days=450),
        "stock_quantity": 30,
        "reorder_level": 10,
        "unit_price": 130.00,
    },
    {
        "brand_name": "Voveran 50mg Tab",
        "drug_name": "Diclofenac Sodium 50mg",
        "category": "Tablet",
        "batch_number": "VOV-2026-291",
        "expiry_date": date.today() + timedelta(days=580),
        "stock_quantity": 110,
        "reorder_level": 20,
        "unit_price": 5.50,
    },
    {
        "brand_name": "Betadine 10% Ointment 20g",
        "drug_name": "Povidone Iodine 10% w/w",
        "category": "Ointment",
        "batch_number": "BET-2026-814",
        "expiry_date": date.today() + timedelta(days=730),
        "stock_quantity": 45,
        "reorder_level": 10,
        "unit_price": 90.00,
    },
    {
        "brand_name": "Dynapar AQ Inj 1ml",
        "drug_name": "Diclofenac Sodium Injection 75mg/ml",
        "category": "Injection",
        "batch_number": "DYN-2026-701",
        "expiry_date": date.today() + timedelta(days=360),
        "stock_quantity": 60,
        "reorder_level": 15,
        "unit_price": 35.00,
    },
    {
        "brand_name": "Ondem 4mg Tab",
        "drug_name": "Ondansetron 4mg",
        "category": "Tablet",
        "batch_number": "OND-2026-642",
        "expiry_date": date.today() + timedelta(days=500),
        "stock_quantity": 80,
        "reorder_level": 15,
        "unit_price": 6.50,
    },
    {
        "brand_name": "Ciplox 500mg Tab",
        "drug_name": "Ciprofloxacin 500mg",
        "category": "Tablet",
        "batch_number": "CIP-2026-419",
        "expiry_date": date.today() + timedelta(days=570),
        "stock_quantity": 90,
        "reorder_level": 15,
        "unit_price": 5.80,
    },
    {
        "brand_name": "Metrogyl 400mg Tab",
        "drug_name": "Metronidazole 400mg",
        "category": "Tablet",
        "batch_number": "MET-2026-302",
        "expiry_date": date.today() + timedelta(days=630),
        "stock_quantity": 130,
        "reorder_level": 20,
        "unit_price": 3.10,
    },
    {
        "brand_name": "Sporidex 500mg Cap",
        "drug_name": "Cephalexin 500mg",
        "category": "Capsule",
        "batch_number": "SPO-2026-522",
        "expiry_date": date.today() + timedelta(days=490),
        "stock_quantity": 40,
        "reorder_level": 10,
        "unit_price": 26.00,
    },
    {
        "brand_name": "Pantocid DSR Cap",
        "drug_name": "Pantoprazole 40mg + Domperidone 30mg",
        "category": "Capsule",
        "batch_number": "PAD-2026-890",
        "expiry_date": date.today() + timedelta(days=610),
        "stock_quantity": 140,
        "reorder_level": 20,
        "unit_price": 15.50,
    },
    {
        "brand_name": "Asthalin 2mg Tab",
        "drug_name": "Salbutamol Sulphate 2mg",
        "category": "Tablet",
        "batch_number": "AST-2026-107",
        "expiry_date": date.today() + timedelta(days=540),
        "stock_quantity": 160,
        "reorder_level": 25,
        "unit_price": 2.20,
    },
    {
        "brand_name": "Deriphyllin Retard 150 Tab",
        "drug_name": "Theophylline 115mg + Etofylline 35mg",
        "category": "Tablet",
        "batch_number": "DER-2026-391",
        "expiry_date": date.today() + timedelta(days=650),
        "stock_quantity": 130,
        "reorder_level": 20,
        "unit_price": 3.60,
    },
    {
        "brand_name": "Ecosprin 75mg Tab",
        "drug_name": "Aspirin (Acetylsalicylic Acid) 75mg",
        "category": "Tablet",
        "batch_number": "ECO-2026-921",
        "expiry_date": date.today() + timedelta(days=700),
        "stock_quantity": 260,
        "reorder_level": 30,
        "unit_price": 1.80,
    },
    {
        "brand_name": "Amlong 5mg Tab",
        "drug_name": "Amlodipine 5mg",
        "category": "Tablet",
        "batch_number": "AML-2026-418",
        "expiry_date": date.today() + timedelta(days=660),
        "stock_quantity": 180,
        "reorder_level": 25,
        "unit_price": 4.50,
    },
    {
        "brand_name": "Atorva 10mg Tab",
        "drug_name": "Atorvastatin Calcium 10mg",
        "category": "Tablet",
        "batch_number": "ATO-2026-731",
        "expiry_date": date.today() + timedelta(days=680),
        "stock_quantity": 150,
        "reorder_level": 20,
        "unit_price": 11.00,
    },
    {
        "brand_name": "Duolin Respules 2.5ml",
        "drug_name": "Levosalbutamol 1.25mg + Ipratropium 500mcg",
        "category": "Inhalation",
        "batch_number": "DUO-2026-809",
        "expiry_date": date.today() + timedelta(days=330),
        "stock_quantity": 75,
        "reorder_level": 15,
        "unit_price": 38.00,
    },
    {
        "brand_name": "Otrivin Adult Nasal Drops 10ml",
        "drug_name": "Xylometazoline Hydrochloride 0.1% w/v",
        "category": "Drops",
        "batch_number": "OTR-2026-215",
        "expiry_date": date.today() + timedelta(days=480),
        "stock_quantity": 35,
        "reorder_level": 10,
        "unit_price": 78.00,
    },
    {
        "brand_name": "Candid Mouth Paint 15ml",
        "drug_name": "Clotrimazole 1% w/v",
        "category": "Drops",
        "batch_number": "CAN-2026-399",
        "expiry_date": date.today() + timedelta(days=420),
        "stock_quantity": 25,
        "reorder_level": 10,
        "unit_price": 82.00,
    },
    {
        "brand_name": "Soframycin Skin Cream 30g",
        "drug_name": "Framycetin Sulphate 1% w/w",
        "category": "Ointment",
        "batch_number": "SOF-2026-611",
        "expiry_date": date.today() + timedelta(days=510),
        "stock_quantity": 40,
        "reorder_level": 10,
        "unit_price": 65.00,
    },
    {
        "brand_name": "Febrex Plus Syrup 60ml",
        "drug_name": "Paracetamol + Phenylephrine + Chlorpheniramine",
        "category": "Syrup",
        "batch_number": "FEB-2026-177",
        "expiry_date": date.today() + timedelta(days=360),
        "stock_quantity": 30,
        "reorder_level": 10,
        "unit_price": 75.00,
    },
    {
        "brand_name": "Kenacort 40mg Inj 1ml",
        "drug_name": "Triamcinolone Acetonide 40mg/ml",
        "category": "Injection",
        "batch_number": "KEN-2026-008",
        "expiry_date": date.today() + timedelta(days=400),
        "stock_quantity": 0,  # Out of stock test
        "reorder_level": 5,
        "unit_price": 145.00,
    },
    {
        "brand_name": "Kenalog 0.1% Oral Paste 5g",
        "drug_name": "Triamcinolone Acetonide 0.1%",
        "category": "Ointment",
        "batch_number": "KNL-2026-052",
        "expiry_date": date.today() + timedelta(days=380),
        "stock_quantity": 8,  # Low stock test
        "reorder_level": 15,
        "unit_price": 92.00,
    },
    {
        "brand_name": "Livogen Adult Tonic 200ml",
        "drug_name": "Iron + Folic Acid Oral Emulsion",
        "category": "Syrup",
        "batch_number": "LIV-2026-993",
        "expiry_date": date.today() + timedelta(days=15),  # Expiring soon test (<30 days)
        "stock_quantity": 22,
        "reorder_level": 10,
        "unit_price": 160.00,
    },
]


def seed_pharmacy_inventory():
    """Seed exactly 50 real-world medicines into the Pharmacy Inventory database"""
    Base.metadata.create_all(bind=engine)
    db = SessionLocal()
    try:
        # Clear existing pharmacy items
        db.query(PharmacyItem).delete()
        db.commit()

        inserted_count = 0
        for med in MEDICINES_DATA:
            item = PharmacyItem(**med)
            db.add(item)
            inserted_count += 1

        db.commit()
        print(f"Successfully seeded {inserted_count} real-world pharmacy inventory items.")
        return inserted_count
    except Exception as e:
        db.rollback()
        print(f"Error seeding pharmacy inventory: {e}")
        raise e
    finally:
        db.close()


if __name__ == "__main__":
    count = seed_pharmacy_inventory()
    print(f"Verified {count} items in database.")
