"""Initial migration

Revision ID: 4cec3b640851
Revises: e7fb4a5465a2
Create Date: 2026-01-24 14:16:49.404157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cec3b640851'
down_revision = 'e7fb4a5465a2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
