"""Initial migration

Revision ID: bcae22ba6cdf
Revises: 4cec3b640851
Create Date: 2026-01-24 14:17:09.301396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcae22ba6cdf'
down_revision = '4cec3b640851'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
