"""Initial migration

Revision ID: e7fb4a5465a2
Revises: 1070cc082031
Create Date: 2026-01-24 14:13:13.817906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7fb4a5465a2'
down_revision = '1070cc082031'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
